version: "3.9"

services:
    node:
      image: aleksey0danilchenko/nodejs2022q4-service-node
      build:
        context: ./
        dockerfile: ./docker/node/Dockerfile
      environment:
        PORT: ${PORT}
        CRYPT_SALT: ${CRYPT_SALT}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
        TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
        TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      ports:
        - target: ${PORT}
          published: ${PORT}
          protocol: tcp
      volumes:
        - .:/usr/src/app:rw,cached
        - ./docker/node/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      restart: on-failure
      networks:
        - database
      depends_on:
        - database

    database:
      image: aleksey0danilchenko/nodejs2022q4-service-database
      build:
        context: ./
        dockerfile: docker/database/Dockerfile
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - ${DB_PORT}:${DB_PORT}
      volumes:
        - db-data:/var/lib/postgresql/data
      restart: on-failure
      networks:
        - database

volumes:
  db-data:

networks:
  database:
