version: "3.9"

services:
    node:
      build:
        context: ./
        dockerfile: ./docker/node/Dockerfile
      environment:
        PORT: ${PORT}
        CRYPT_SALT: ${CRYPT_SALT}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
        TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
        TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      ports:
        - target: ${PORT}
          published: ${PORT}
          protocol: tcp
      volumes:
        - .:/usr/src/app:rw,cached
        - ./docker/node/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      restart: on-failure

    database:
      build:
        context: ./
        dockerfile: docker/database/Dockerfile
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - db-data:/var/lib/postgresql/data
      restart: on-failure

volumes:
  db-data:
